// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvhslqwsijnoxajnujzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aHNscXdzaWpub3hham51anp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjYwMjQsImV4cCI6MjA2NTkwMjAyNH0.MUtSga0YQRB2yqur77GoZ19MCvtXytdW152b6jpsI9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);